# ============================================================
# CRIA AS TABELAS NO SUPABASE AUTOMATICAMENTE
# ------------------------------------------------------------
# Cria:  painel_inv  (dados compartilhados do Painel de Investigacoes)
#        infratores  (dados da aba Infratores - opcional)
#
# COMO USAR:
#  1) Gere um token pessoal em:
#        https://supabase.com/dashboard/account/tokens
#     (botao "Generate new token" -> copie o valor que comeca com sbp_)
#  2) Rode no PowerShell, nesta pasta:
#        .\setup_supabase.ps1 -Token "sbp_xxxxxxxxxxxxxxxx"
#
#  O token e usado so localmente para criar as tabelas. Apos rodar,
#  voce pode revoga-lo no mesmo lugar, se quiser.
# ============================================================
param([Parameter(Mandatory=$true)][string]$Token)

$ErrorActionPreference = 'Stop'
$ref = 'rfwmklqzlfvllsrkvgob'
$api = "https://api.supabase.com/v1/projects/$ref/database/query"
$headers = @{ Authorization = "Bearer $Token"; 'Content-Type' = 'application/json' }

$sql = @"
-- Painel de Investigacoes (compartilhado)
create table if not exists public.painel_inv (
  id int primary key,
  data jsonb,
  updated_at timestamptz default now()
);
alter table public.painel_inv enable row level security;
drop policy if exists "painel_inv_auth_all" on public.painel_inv;
create policy "painel_inv_auth_all" on public.painel_inv
  for all to authenticated using (true) with check (true);

-- Infratores (protegido - aba Infratores)
create table if not exists public.infratores (
  id bigint generated by default as identity primary key,
  nome text, status text, org text, cidade text, trecho text, dt text,
  la double precision, lo double precision,
  mae text, pai text, cpf text, bo text
);
alter table public.infratores enable row level security;
drop policy if exists "infratores_auth_select" on public.infratores;
create policy "infratores_auth_select" on public.infratores
  for select to authenticated using (true);
"@

$body = @{ query = $sql } | ConvertTo-Json

try {
  $r = Invoke-RestMethod -Uri $api -Method Post -Headers $headers -Body $body -TimeoutSec 60
  Write-Host "TABELAS CRIADAS COM SUCESSO!" -ForegroundColor Green
  Write-Host "  - painel_inv (compartilhamento do Painel de Investigacoes)"
  Write-Host "  - infratores (aba Infratores)"
  Write-Host ""
  Write-Host "Agora: abra o painel, faca login, e os dados ja ficam compartilhados."
} catch {
  Write-Host "FALHA: $($_.Exception.Message)" -ForegroundColor Red
  $resp = $_.Exception.Response
  if ($resp) { $sr = New-Object System.IO.StreamReader($resp.GetResponseStream()); Write-Host $sr.ReadToEnd() }
  Write-Host ""
  Write-Host "Verifique se o token (sbp_...) esta correto e tem acesso ao projeto." -ForegroundColor Yellow
}
